### ISSUE TITLE
B2BUA Message Manipulation

### ISSUE THREAD

**Issue by salihy** [davehorton/simple-drachtio-registrar#1]
Hi,

Is it possible to manipulate messages when our app act as B2BUA?

**Comment by davehorton** [comment]
Depends exactly what you want to do, please see the api docs for [srf.createB2BUA](https://drachtio.org/api#srf-create-b2bua).

You can do any of the following:
1.  Copy some or all of the headers from the A leg invite to the B leg invite.
2. Copy some or all of the headers from the B leg response to the A leg response.
3. Add new headers to the B leg invite
4. Manipulate the SDP offered by A before sending it to B
5. Manipulate the SDP answered by B before sending it to A.
6.  If B responds with non-success, you can choose *not* to send that back to A and instead attempt a different server / sip endpoint for the B leg.

Are any of those the things you are thinking about?  If your scenario / needs are different let me know

**Comment by salihy** [comment]
I want to implement message manipulation features of SBCs. Is it possible to implement converting refer message to re-invite message?

**Comment by davehorton** [comment]
Yes, once you have established a back to back dialogs, you can listen for the ['refer' event](https://drachtio.org/api#dialog-event-refer) on the uas [dialog](https://drachtio.org/api#dialog) (e.g. the A leg), and when you get a REFER request then:
* send a 202 Accepted to the refer
* generate a new INVITE to the Refer-To number using [srf.createUAC](https://drachtio.org/api#srf-create-uac), providing the SDP of the existing uac dialog
* when answered, call [uac.modify](https://drachtio.org/api#dialog-modify) so that the original uac leg now is sending media to the new party
* send a BYE on the original uas leg by calling [uas.destroy](https://drachtio.org/api#dialog-destroy), or if you prefer send NOTIFYs to it first and then send a BYE

Actually I suppose you could listen for the REFER on either leg since either might initiate a transfer

**Comment by salihy** [comment]
Hi Dave,

I have in my hang working example of this setup with an another solution, you can find it image attached. What I require is to find out how to manipulate messages. How can I listen events for every sip messages and how to manipulate them.

Thanks in advance

![capture](https://user-images.githubusercontent.com/4982519/42257758-cfe0ffb2-7f60-11e8-9db0-b91fccafbc03.PNG)

**Comment by salihy** [comment]
Thanks, I will try and let you know.

**Comment by salihy** [comment]
Hi, I have done every step like you described, SIP messaging works but I think there is a problem with RTP. After new UAC connection established, I cannot establish RTP traffic between two uac's. There is a network capture directly from drachtio-server, and you can find my repository from https://github.com/salihy/Drachtio_B2BMessageManipulation.
[log.zip](https://github.com/davehorton/simple-drachtio-registrar/files/2163224/log.zip)

**Comment by salihy** [comment]
I figured it out, thanks for your help.

**Comment by davehorton** [comment]
Great.  It looked like a case of just making sure the correct SDP was offered to the new leg on the INVITE after the refer.

For reference sake, and to illustrate a few things, I took a shot at how I would do this.  This is untested, but simplifies a few things:
```js
const config = require('config');
const Srf = require('drachtio-srf');
const srf = new Srf();

srf.connect(config.get('drachtio'))
  .on('connect', (err, hostport) => {
    if (err) return console.error(`error connecting: ${err.message}`);
    console.log(`connected hostport: ${hostport}`);
  });

srf.register((req, res) => {
  res.send(200);
});

// example use of middleware to authenticate and stuff like that
srf.use('invite', (req, res, next) => {
  console.log(`incoming invite from ${req.source_address} with uri ${req.uri}`);
  if (!config.get('sipservers').some((w) => w.ip == req.source_address)) {
    return res.send(580, 'Sip Server Is Not Authenticated!');
  }
  next();
});

srf.invite((req, res) => {
  // at this point we have an authenticated request
  const uri = `${config.get('destination')};transport=udp`;
  srf.createB2BUA(req, res, uri)
    .then(({ uac, uas }) => {
      console.log(`call connected, initial call-ids ${uas.sip.callId} and ${uac.sip.callId}`);

      // we always have a pair of dialogs, so lets have each have a ref to the other
      uas.other = uac;
      uac.other = uas;
      setHandlers([uac, uas]);
      return;

    })
    .catch((err) => {
      console.log(`Error connecting call: ${err}`);
    });
});

function setHandlers(dialogs) {
  dialogs = Array.isArray(dialogs) ? dialogs : [dialogs];

  dialogs.forEach((dlg) => {
    dlg
      .on('destroy', () => dlg.other.destroy())
      .on('modify', (req, res) => {
        dlg.other.modify(req.body)
          .then(() => res.send(200, {body: dlg.other.remote.sdp}))
          .catch((err) => console.log(`Error handling reinvite: ${err}`));
      })
      .on('refer', handleRefer.bind(dlg));
  });
}
function handleRefer(req, res) {
  console.log(`handling refer on ${req.get('Call-ID')}`);
  const uri = req.get('refer-to').replace('<sip:', '').replace('>', '');
  return srf.createUAC(uri, {localSdp: this.other.remote.sdp})
    .then((dlg) => {
      console.log(`Connected new call leg on ${dlg.sip.callId}`);
      dlg.other = this.other;
      this.other.other = dlg;
      this.destroy();
      setHandlers(dlg);
      return;
    });
}
```
A few things I noted in the original code:
* no need to include `drachtio-sip` as a dependency any more.  If you need the `parseUri` function it is available on the [Srf class](https://drachtio.org/api#Srf-properties)
* instead of referring to `req.msg.body` just `req.body` as a short cut
* instead of `msg.headers[hdrName]` you can use `msg.get(hdrName)`
* there is no `request` event on the Srf instance.

**Comment by salihy** [comment]
Thank you, that will help.

**Comment by davehorton** [comment]
I saw a few errors in my sample code above, so I've just updated - make sure to try the latest if you are going to test it

**Comment by salihy** [comment]
Thanks, I will try. Btw, your work is great and helps me a a lot with my job.

**Comment by davehorton** [comment]
Oh great!  I'm glad to hear that 👍
